- name: Rescan HBA's 
  vmware_host_scanhba:
      hostname: '{{ vcenter_hostname }}'
      username: '{{ username }}'
      password: '{{ password }}'
      cluster_name: '{{ Cluster }}'
      refresh_storage: true
      validate_certs: no
  delegate_to: localhost
